#!/usr/bin/env bash
# Emit the Homebrew formula for a release to stdout.
#
#   ./scripts/update-homebrew-formula.sh 0.1.0 checksums.txt > voom.rb
#
# The checksums file is the `voom_<version>_checksums.txt` asset produced by the
# `checksums` job in .github/workflows/publish.yaml. The result is committed to
# Goldziher/homebrew-tap as Formula/voom.rb.
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: $0 <version> <checksums-file>" >&2
  exit 2
fi

VERSION="$1"
SUMS="$2"

[[ -f "$SUMS" ]] || { echo "checksums file not found: $SUMS" >&2; exit 1; }

BASE="https://github.com/Goldziher/voom/releases/download/v${VERSION}"

sha_for() {
  awk -v f="voom-$1.tar.gz" '{n=$NF; sub(/^[*]/, "", n); if (n == f) print $1}' "$SUMS"
}

MAC_ARM="$(sha_for aarch64-apple-darwin)"
MAC_X64="$(sha_for x86_64-apple-darwin)"
LINUX_ARM="$(sha_for aarch64-unknown-linux-gnu)"
LINUX_X64="$(sha_for x86_64-unknown-linux-gnu)"

for pair in "aarch64-apple-darwin:$MAC_ARM" "x86_64-apple-darwin:$MAC_X64" \
            "aarch64-unknown-linux-gnu:$LINUX_ARM" "x86_64-unknown-linux-gnu:$LINUX_X64"; do
  triple="${pair%%:*}"
  sum="${pair#*:}"
  if [[ -z "$sum" ]]; then
    echo "no checksum for voom-${triple}.tar.gz in $SUMS" >&2
    exit 1
  fi
done

cat <<EOF
# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh — do not edit by hand.
class Voom < Formula
  desc "Fast, safe, parallel build-artifact pruning across every major language ecosystem"
  homepage "https://github.com/Goldziher/voom"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE}/voom-aarch64-apple-darwin.tar.gz"
      sha256 "${MAC_ARM}"
    end
    on_intel do
      url "${BASE}/voom-x86_64-apple-darwin.tar.gz"
      sha256 "${MAC_X64}"
    end
  end

  on_linux do
    on_arm do
      url "${BASE}/voom-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${LINUX_ARM}"
    end
    on_intel do
      url "${BASE}/voom-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${LINUX_X64}"
    end
  end

  def install
    bin.install "voom"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/voom --version")
  end
end
EOF
